#builder
FROM maven:latest AS maven_builder
ENV TARGET_ENV="test"
RUN echo 'Building diggester...'> /build.txt
WORKDIR /usr/mqttstreamdigest/
COPY . .
COPY ./*.properties ./src/main/resources/
RUN echo 'spring.profiles.active='${TARGET_ENV} > ./src/main/resources/application.properties
#RUN echo '-Dhttps.protocols=TLSv1.2' > ./jvm.config
RUN mvn package


#backend App
FROM eclipse-temurin:latest
WORKDIR /app
COPY --from=maven_builder /usr/mqttstreamdigest/target/mqtt-stream-digest-0.0.1-SNAPSHOT.jar .

EXPOSE 8081
ENTRYPOINT ["java","-jar","/app/mqtt-stream-digest-0.0.1-SNAPSHOT.jar"]