version: "3.8"
services:
  
  #IoT Agent
  iot-agent:
    image: quay.io/fiware/iotagent-json:latest
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
        - mongo-db
    networks:
        - default
    expose:
        - '4041'
        - '7896'
    ports:
    #Port 4041 is exposed purely for tutorial access - so that cUrl or Postman can make provisioning commands without being part of the same network
        - '4041:4041'        
        - '7896:7896'
    environment:
        - IOTA_CB_HOST=orion
        - IOTA_CB_PORT=1026
        - IOTA_NORTH_PORT=4041
        - IOTA_REGISTRY_TYPE=mongodb
        - IOTA_LOG_LEVEL=DEBUG
        - IOTA_TIMESTAMP=true
        - IOTA_CB_NGSI_VERSION=v2
        - IOTA_AUTOCAST=true
        - IOTA_MONGO_HOST=mongo-db
        - IOTA_MONGO_PORT=27017
        - IOTA_MONGO_DB=iotagentjson
        - IOTA_HTTP_PORT=7896
        - IOTA_PROVIDER_URL=http://iot-agent:4041
        - IOTA_DEFAULT_RESOURCE=/iot/json

  # context broker
  orion:
    labels:
      org.fiware: 'mobox_backend'
    image: fiware/orion:3.10.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - default
    ports:
      - "1026:1026"  # containerPort:localPort
    command: -dbhost mongo-db -logLevel DEBUG -noCache


  # Database
  mongo-db:
    labels:
      org.fiware: 'mobox_backend'
    #image: mongo:4.2
    image: mongo
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - mongo-db:/data/db
    

  #Grafana Dashboard
  grafana:
    labels:
      org.fiware: 'mobox_backend'
    #image: grafana/grafana-oss:10.4.2-ubuntu
    build: ./grafana
    container_name: build-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana:/var/lib/grafana
    networks:
      - default
    
  #MQTT
  mosquitto:
    #image: eclipse-mosquitto:1.6.14
    image: eclipse-mosquitto:2
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
  
  morpheus-agent:
    build: ./morpheusagent/.
    container_name: morpheus-agent
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - default
  
  mqtt-diggester:
    build: ./mqttstreamdigest/.
    container_name: diggester-mqtt
    depends_on:
      - morpheus-agent
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - default

networks:
  default:
    labels:
      org.fiware: 'mobox_backend'
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  grafana: ~
  mongo-db: ~
  crate-db: ~
